# Generated by Django 5.2.1 on 2025-05-12 05:21

import config.models.base_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.TextField()),
                ("content", models.TextField()),
                ("full_url", models.URLField(blank=True, null=True)),
                ("site_url", models.URLField(blank=True, null=True)),
                ("author", models.TextField()),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="problem.problem",
                    ),
                ),
            ],
            options={
                "db_table": "articles",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
