# Generated by Django 5.2.1 on 2025-05-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0002_article_code_article_enhanced_explanation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="code",
        ),
        migrations.RemoveField(
            model_name="article",
            name="enhanced_explanation",
        ),
        migrations.AddField(
            model_name="article",
            name="additional_tips",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="approach",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="code_blocks",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="complexity_analysis",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="problem_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="relevance_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
