# Generated by Django 5.2.1 on 2025-05-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("article", "0003_remove_article_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="content",
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.TextField(blank=True, null=True),
        ),
    ]
