# Generated by Django 5.2.1 on 2025-05-12 05:21

import config.models.base_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProblemCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.TextField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "problem_categories",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="Problem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("boj_id", models.IntegerField(unique=True)),
                ("title", models.TextField()),
                ("description", models.TextField(blank=True, null=True)),
                ("input_description", models.TextField()),
                ("output_description", models.TextField()),
                ("extra_information", models.TextField(blank=True, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="problems",
                        to="problem.problemcategory",
                    ),
                ),
            ],
            options={
                "db_table": "problems",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
        migrations.CreateModel(
            name="ProblemTestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("input_data", models.TextField()),
                ("output_data", models.TextField()),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_cases",
                        to="problem.problem",
                    ),
                ),
            ],
            options={
                "db_table": "problem_test_cases",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
