# Generated by Django 5.2.1 on 2025-05-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="problem",
            name="level",
            field=models.IntegerField(default=0),
        ),
    ]
