# Generated by Django 5.2.1 on 2025-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0002_problem_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problem",
            name="extra_information",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
