# Generated by Django 5.2.1 on 2025-05-14 04:39

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0003_alter_problem_extra_information"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["boj_id"], name="problems_boj_id_b8301f_idx"),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["title"], name="problems_title_2b1ea9_idx"),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=models.Index(fields=["level"], name="problems_level_b0e434_idx"),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["title"], name="problems_title_18b6c1_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="problem",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["boj_id"], name="problems_boj_id_258f08_gin"
            ),
        ),
    ]
