# Generated by Django 5.2.1 on 2025-05-26 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0004_problem_problems_boj_id_b8301f_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="problemtestcase",
            name="input_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="problemtestcase",
            name="output_data",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="problemtestcase",
            name="problem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_cases",
                to="problem.problem",
            ),
        ),
    ]
