# Generated by Django 5.2.1 on 2025-06-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0005_alter_problemtestcase_input_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="problemtestcase",
            name="is_official",
            field=models.BooleanField(default=False),
        ),
    ]
