# Generated by Django 5.2.1 on 2025-06-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0006_problemtestcase_is_official"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="problemtestcase",
            managers=[],
        ),
    ]
