# Generated by Django 5.2.1 on 2025-06-05 04:25

import config.models.base_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("problem", "0007_alter_problemtestcase_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProblemCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("solution_code", models.TextField()),
                ("validation_code", models.TextField()),
                ("language", models.CharField(default="python", max_length=20)),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problem.problem",
                    ),
                ),
            ],
            options={
                "db_table": "problem_codes",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
