# Generated by Django 5.2.1 on 2025-05-12 10:28

import uuid

import config.models.base_model
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("problem", "0003_alter_problem_extra_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("code", models.TextField()),
                ("language", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "problem",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="problem.problem",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
