# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: judger.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 6, 30, 0, "", "judger.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0cjudger.proto\x12\x0b\x63ode_judger"\x99\x01\n\x0cJudgeRequest\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x17\n\x0ftimeout_seconds\x18\x04 \x01(\x05\x12\x17\n\x0fmemory_limit_mb\x18\x05 \x01(\x05\x12\r\n\x05input\x18\x06 \x03(\t\x12\x17\n\x0f\x65xpected_output\x18\x07 \x03(\t"\xe4\x01\n\rJudgeResponse\x12\x0f\n\x07\x63orrect\x18\x01 \x01(\x08\x12\x15\n\ractual_output\x18\x02 \x01(\t\x12\x17\n\x0f\x65xpected_output\x18\x03 \x01(\t\x12\x0e\n\x06stdout\x18\x04 \x01(\t\x12\x0e\n\x06stderr\x18\x05 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x06 \x01(\x01\x12\x16\n\x0ememory_used_kb\x18\x07 \x01(\x05\x12\x15\n\rerror_message\x18\x08 \x01(\t\x12(\n\x06status\x18\t \x01(\x0e\x32\x18.code_judger.JudgeStatus*z\n\x0bJudgeStatus\x12\x11\n\rJUDGE_UNKNOWN\x10\x00\x12\x11\n\rJUDGE_CORRECT\x10\x01\x12\x0f\n\x0bJUDGE_WRONG\x10\x02\x12\x11\n\rJUDGE_TIMEOUT\x10\x03\x12\x10\n\x0cJUDGE_MEMORY\x10\x04\x12\x0f\n\x0bJUDGE_ERROR\x10\x05\x32P\n\nCodeJudger\x12\x42\n\tJudgeCode\x12\x19.code_judger.JudgeRequest\x1a\x1a.code_judger.JudgeResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "judger_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_JUDGESTATUS"]._serialized_start = 416
    _globals["_JUDGESTATUS"]._serialized_end = 538
    _globals["_JUDGEREQUEST"]._serialized_start = 30
    _globals["_JUDGEREQUEST"]._serialized_end = 183
    _globals["_JUDGERESPONSE"]._serialized_start = 186
    _globals["_JUDGERESPONSE"]._serialized_end = 414
    _globals["_CODEJUDGER"]._serialized_start = 540
    _globals["_CODEJUDGER"]._serialized_end = 620
# @@protoc_insertion_point(module_scope)
