# Generated by Django 5.2.1 on 2025-05-14 03:01

import config.models.base_model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_usage_per_day", models.PositiveIntegerField(default=50)),
                ("max_usage_per_month", models.PositiveIntegerField(default=5000)),
                ("max_usage_per_year", models.PositiveIntegerField(default=50000)),
                ("max_usage_per_lifetime", models.PositiveIntegerField(default=500000)),
                ("usage_per_day", models.IntegerField(default=0)),
                ("usage_per_month", models.IntegerField(default=0)),
                ("usage_per_year", models.IntegerField(default=0)),
                ("usage_per_lifetime", models.IntegerField(default=0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ticket",
                "verbose_name_plural": "tickets",
                "db_table": "tickets",
            },
            managers=[
                ("objects", config.models.base_model.BaseModelManager()),
            ],
        ),
    ]
