# Generated by Django 5.2.1 on 2025-05-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_ticket_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="plan_type",
            field=models.CharField(
                choices=[("basic", "Basic"), ("plus", "Plus"), ("pro", "Pro")],
                default="basic",
                max_length=10,
                verbose_name="Plan Type",
            ),
        ),
    ]
